# Base URL configuration
baseURL: "https://jwogrady.github.io/status26.com/"
title: Papermod
copyright: "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
theme: github.com/jwogrady/hugo-theme-papermod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

# Updated pagination configuration
pagination:
  pagerSize: 5

minify:
  disableXML: true

# Multi-language support
languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: WiKi
          url: https://github.com/adityatelange/hugo-PaperMod/wiki/

  fr:
    languageName: ":fr:"
    weight: 2
    title: PaperModL2
    taxonomies:
      category: FRcategories
      tag: FRtags
      series: FRseries
    menu:
      main:
        - name: Archive
          url: archives/
          weight: 5
        - name: FRTags
          url: frtags
          weight: 10
        - name: FRCategories
          url: frcategories
          weight: 10
        - name: FRSeries
          url: frseries
          weight: 10
        - name: NullLink
          url: "#"

  fa:
    languagedirection: rtl
    weight: 3
    title: PaperMod RTL
    taxonomies:
      category: FAcategories
      tag: FAtags
      series: FAseries
    menu:
      main:
        - name: FATags
          url: fatags
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Theme PaperMod

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  homeInfoParams:
    Title: "PaperMod's Demo"
    Content: >
      👋 Welcome to the demo page of Hugo's theme PaperMod!

      - **PaperMod** is designed to be clean, simple, fast, and responsive.
      - Feel free to show your support by giving us a star 🌟 on GitHub and sharing it on social media.

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/adityatelange/hugo-PaperMod"
    - name: Discord
      title: Join Discord community
      url: "https://discord.gg/ahpmTvhVmp"
    - name: X
      title: Share PaperMod on X/Twitter
      url: "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"

  editPost:
    URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
    Text: "Suggest Changes"
    appendFilePath: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true